name: Azure Production Deployment

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'drizzle/**'
      - 'public/**'
      - 'src/**'
      - 'bun.lock'
      - 'compose.yaml'
      - 'Dockerfile'
      - 'drizzle.config.ts'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.ts'

permissions:
  contents: read
  deployments: write
  packages: write

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ vars.APP_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Vite Plus
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 22
          cache: true

      - name: Detect migration changes
        id: migrate_changes
        uses: dorny/paths-filter@v4
        with:
          filters: |
            migrate:
              - 'drizzle/**'
              - 'bun.lock'
              - 'drizzle.config.ts'
              - 'package.json'

      - name: Install dependencies
        run: vp install

      - name: Build
        run: vp build

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push container to GHCR
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ausathdzil/forge:latest

      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to Azure VM
        env:
          HOST: ${{ secrets.TAILNET_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          RUN_MIGRATIONS: ${{ steps.migrate_changes.outputs.migrate == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
            cd /srv/forge
            docker compose pull
            docker compose up -d
          EOF
